import os

import numpy as np
from keras.models import load_model

from train_lstm import Vectorizer

if __name__ == '__main__':
    model = load_model(os.path.join('data', 'name_model.h5'))

    vectorizer = Vectorizer()

    strings_to_try = {
        'Abathur',
        'Arthas',
        'Diablo',
        'E.T.C.',
        'Gazlowe',
        'Illidan',
        'Kerrigan',
        'Malfurion',
        'Muradin',
        'Nazeebo',
        'Nova',
        'Raynor',
        'Sgt. Hammer',
        'Sonya',
        'Stitches',
        'Tassadar',
        'Tyrael',
        'Tyrande',
        'Uther',
        'Valla',
        'Zeratul',
        'Tychus',
        'Brightwing',
        'Li Li',
        'Murky',
        'Arthas',
        'Diablo',
        'E.T.C.',
        'Falstad',
        'Gazlowe',
        'Illidan',
        'Kerrigan',
        'Li Li',
        'Sgt. Hammer',
        'Sonya',
        'Tassadar',
        'Tychus',
        'Tyrael',
        'Tyrande',
        'Uther',
        'Zagara',
        'Zeratul',
        'Rehgar',
        'Chen',
        'Zagara',
        'Anub\'arak',
        'Azmodan',
        'Chen',
        'E.T.C.',
        'Li Li',
        'Azmodan',
        'Jaina',
        'Jaina',
        'Thrall',
        'Stitches',
        'Thrall',
        'The Lost Vikings',
        'Sylvanas',
        'Sylvanas',
        'Kael\'thas',
        'Johanna',
        'Johanna',
        'Murky',
        'The Butcher',
        'Leoric',
        'Brightwing',
        'Kharazim',
        'Rexxar',
        'Chen',
        'Tyrael',
        'Lt. Morales',
        'Artanis',
        'Cho\'gall',
        'Jaina',
        'Lunara',
        'Zagara',
        'Lunara',
        'Cho\'gall',
        'Greymane',
        'Greymane',
        'Johanna',
        'Li-Ming',
        'Li-Ming',
        'Thrall',
        'Xul',
        'Xul',
        'Dehaka',
        'Kerrigan',
        'Dehaka',
        'The Butcher',
        'Tracer',
        'Tracer',
        'Tracer',
        'Chromie',
        'Nazeebo',
        'Nova',
        'Chromie',
        'Lunara',
        'Medivh',
        'Medivh',
        'Gul\'dan',
        'Kael\'thas',
        'Gul\'dan',
        'Auriel',
        'Thrall',
        'Tyrande',
        'Uther',
        'Alarak',
        'Azmodan',
        'Gazlowe',
        'Alarak',
        'Diablo',
        'Muradin',
        'Zarya',
        'Zarya',
        'Samuro',
        'Greymane',
        'Rexxar',
        'Samuro',
        'Varian',
        'Leoric',
        'Varian',
        'Ragnaros',
        'Sylvanas',
        'Zul\'jin',
        'Valeera',
        'Lúcio',
        'Kharazim',
        'Lúcio',
        'Probius',
        'Cassia',
        'Genji',
        'D.Va',
        'Malthael',
        'Stukov',
        'Garrosh',
        'Kel\'Thuzad',
    }
    strings_to_try = [
        'Bogdana',
        'Bogdan'
    ]
    strings_to_try = vectorizer.preprocess_strings(strings_to_try, vectorizer.max_string_length)
    for s in strings_to_try:
        vector = vectorizer.vectorize_string(s)
        vector = np.array([vector])
        prediction = model.predict(vector)
        prediction = prediction[0][0]
        prediction_label = 'boy' if prediction < 0.5 else 'girl'
        prediction_confidence = 1 - prediction if prediction_label == 'boy' else prediction
        print(
            '{0:<20} {1:.1f}% {2}'.format(
                s, prediction_confidence * 100, prediction_label
            )
        )
